GET {{host}}/api/Categories?PageNumber=1&PageSize=100
content-Type: application/json

###
@ParentCategoryId = 1333
GET {{host}}/api/Categories/{{ParentCategoryId}}/subcategories?ParentCategoryId={{ParentCategoryId}}&PageNumber=1&PageSize=10


### POST
POST {{host}}/api/Categories
content-Type: application/json

{
  "Name": "Test Category3",
  "ParentCategoryId": 1333
}
